format_version: 10
pipelines:
  RunExecutableUsingCode.gocd:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-da00413:
        git: https://github.com/ankit68543/ExecutableCICD.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - Build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build:
            timeout: 0
            tasks:
            - exec:
                  command: dotnet
                  args: ["build", "ExecutableCICD/ExecutableCICD.csproj"]
                  run_if: passed
              - exec:
                  command: dotnet
                  args: ["publish", "ExecutableCICD/ExecutableCICD.csproj"]
                  run_if: passed
                
